apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: partner-partner-endorser-transaction
  annotations:
    flux.weave.works/automated: "false"
  namespace: partner-ns
spec:
  releaseName: partner-partner-endorser-transaction
  chart:
    path: platforms/hyperledger-indy/charts/indy-ledger-txn
    git: ssh://git@github.com/hriday-tiwari/blockchain-automation-framework.git
    ref: develop
  values:
    metadata:
      name: partner-partner-endorser-transaction
      namespace: partner-ns
    network:
      name: baf
    image:
      cli:
        name: partner
        repository: index.docker.io/hyperledgerlabs/indy-ledger-txn:latest
        pullSecret: regcred
    vault:
      address: http://afeeb769d72df4df8a463dd79324f7b6-63398814.us-east-1.elb.amazonaws.com:9000
      role: rw
      serviceAccountName: partner-admin-vault-auth
      auth_path: kubernetes-partner-admin-auth
    organization:
      name: partner
      adminIdentity:
        name: authority-trustee
        did: VH4ZLRo69pyQBJtsVt2RHj
        path: authority/trustees
      newIdentity:
        name: partner-endorser
        role: ENDORSER
        did: Fqh9KpKW9MzUBXo5faHF32
        verkey: 967B9dFBbpmcQ8uXkiApjSnDAhY6yC4MAwJ474BUEMfg
        path: partner/endorsers
    node:
      name: partner
